#!/bin/bash echo "ALX School is so cool!"
#!/bin/bash echo "ALX School is so cool!"
e66c30f43f449416f53aec9915ad6a492a624437
#!/bin/bash echo "ALX School is so cool!"
#!/bin/bash echo "ALX School is so cool!"
afa206d4906049db30a30e812aebf786d831b748
